# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
general:
  branches:
    only:
     - master # list of branches to build
     - /feature-.*/ # or regexes

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.5.5
        environment:
          RAILS_ENV: test
          PG_HOST: 127.0.0.1
          PG_USER: root

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/postgres:9.5
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: rideshare_test

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: bundle install --path=vendor/bundle || bundle install --path=vendor/bundle --jobs 4 --retry 3

      - save_cache:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Database setup
      - run:
        name: Set up DB
        command: |
          bundle exec rake db:create db:schema:load --trace
          bundle exec rake db:migrate
        environment:
          DATABASE_URL: "postgres://ubuntu@localhost:5432/rideshare_test"

      # run tests!
      - run:
          name: run tests
          command: bin/rails test

      # collect reports
      - store_test_results:
          path: /tmp/test-results
